### ISSUE TITLE
Form submission on button click does not seem to work

### ISSUE THREAD

**Issue by RensDimmendaal** [AnswerDotAI/fh-frankenui#14]
Hi there,

I've been experimenting with this library today and I like the direction it's heading! Thanks for your work on it!

There's this one simple thing that I'm trying to do and I cant seem to get it to work: submitting forms on button click.

Below is a minimal example.
The code below runs, however if I uncomment the fh_frankenui.core import then the form submission button does not work anymore.
But, if I uncomment the hx_trigger line, then form submissions does occur after a short delay, but still not via the button.

Do you know what I'm doing wrong?

Looking forward to see this library evolve!

```python
from fasthtml.common import *
# from fh_frankenui.core import *  # <-- uncommenting breaks the form submit button functionality

app = FastHTML()

@app.get("/")
def home():
    return (
        Form(
            hx_post="/submit",
            hx_target="#target",
            # hx_trigger="keyup changed delay:1s"  # this feature still works w fh_frankenui
        )(
            Input(id="name", label="Name", placeholder="Enter your name", type="string"),
            Button("Submit!")
        ),
        P("Hello!", id="target")
    )

@app.post("/submit")
def submit(name: str):
    return P(f"Hello, {name}!", id="target")


serve()

```

**Comment by RensDimmendaal** [comment]
I refreshed my install now it works. Sorry for the noise :)

**Comment by RensDimmendaal** [comment]
I closed the issue because I thought it was an issue on my end...but I did some more checks and I do believe there's something in fh_frankenui that's not working as expected...

**Comment by Isaac-Flath** [comment]
Awesome, thank you so much for diving in.  Please continue to create issues for anything annoying/clunky even if you don't have a solution!  Improving the developer experience in the API is very important.

In this case you had a solution that I completely agree with.  Try it out and let me know how it works for you!

<img width="790" alt="Screenshot 2024-10-24 at 7 44 23 PM" src="https://github.com/user-attachments/assets/0e623ae6-1f9c-4c36-bb48-7b640392e5d2">
