### ISSUE TITLE
Docs missing fh-matplotlib dependency

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fh-frankenui#16]
1. Go to docs/apps
2. `python main.py` throws this error:

```python
❯ python main.py 
Traceback (most recent call last):
  File "/Users/drg/answer/fh-frankenui/docs/app/main.py", line 41, in <module>
    from dashboard import dashboard_homepage
  File "/Users/drg/answer/fh-frankenui/docs/app/dashboard.py", line 16, in <module>
    from fh_matplotlib import matplotlib2fasthtml
ModuleNotFoundError: No module named 'fh_matplotlib'
```

`docs/app/requirements.txt` isn't specified or documented anywhere.

**Comment by Isaac-Flath** [comment]
I'm reworking how docs are done generally to try to make it more friendly to contributors.  I've simplified the docs to be a regular app with py files, and updated the contributing guide.  I think there's more I need to do here, but hopefully contributing will get easier and easier so please let me know all the stumbling blocks you see :)
